version: '3.3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=diu
      - POSTGRES_USER=diu
      - POSTGRES_PASSWORD=diu
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  
  django:
    build: ./django
    devices:
      - /dev/ttyS0:/dev/ttyS0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/djangoapp
    ports:
      - "8000:8000"
    depends_on:
      - db
      - node
      - celery

  celery:
    build: ./django
    command: celery worker -A diufirstprocjet -l info
    volumes:
      - ./django:/djangoapp
    depends_on:
      - redis

  node:
    build: ./node
    volumes:
      - ./node:/nodeapp
    depends_on:
      - redis
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django

  redis:
    image: redis

volumes:
  db_data:
    external: true