# Generated by Django 2.2.3 on 2019-07-28 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, 'Mínimo 6 carateres.')])),
                ('info_personaje', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Mínimo 6 carateres.')])),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5, 'Mínimo 8 dígitos.')])),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Personaje')),
            ],
        ),
    ]
