# Generated by Django 2.2.3 on 2019-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('statement', models.CharField(max_length=512)),
                ('answer_1', models.CharField(blank=True, max_length=512, null=True)),
                ('answer_2', models.CharField(blank=True, max_length=512, null=True)),
                ('answer_3', models.CharField(blank=True, max_length=512, null=True)),
                ('answer_4', models.CharField(blank=True, max_length=512, null=True)),
                ('answer_5', models.CharField(blank=True, max_length=512, null=True)),
                ('correct_answer', models.CharField(max_length=32)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
    ]
