# Generated by Django 2.2.3 on 2019-07-29 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=512),
        ),
    ]
