# Generated by Django 2.2.3 on 2019-08-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, 'Mínimo 6 carateres.')])),
                ('info', models.TextField(max_length=1024, validators=[django.core.validators.MinLengthValidator(6, 'Mínimo 6 carateres.')])),
                ('card', models.CharField(max_length=128)),
                ('questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
